export const wallpaperCities = [
	{
		name: 'Toronto',
		folder: 'toronto',
		slug: 'toronto',
		hero: 'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
		gallery: [
			'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
			'luxury-boardroom-wallpaper-installation-toronto-executive-meeting-room.png',
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
		],
	},
	{
		name: 'Vaughan',
		folder: 'vaughan',
		slug: 'vaughan',
		hero: 'dark-luxury-lounge-wallpaper-installation-vaughan-moody-feature-wall.jpg',
		gallery: [
			'dark-luxury-lounge-wallpaper-installation-vaughan-moody-feature-wall.jpg',
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
			'home-library-wallpaper-installation-vaughan-dark-accent-reading-room.png',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
			'dining-room-wallpaper-installation-vaughan-soft-floral-luxury-space.png',
			'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
		],
	},
	{
		name: 'Richmond Hill',
		folder: 'richmond-hill',
		slug: 'richmond-hill',
		hero: 'custom-library-wallpaper-installation-richmond-hill-built-in-bookshelves.jpg',
		gallery: [
			'custom-library-wallpaper-installation-richmond-hill-built-in-bookshelves.jpg',
			'home-office-wallpaper-installation-richmond-hill-bright-study-bookshelves.jpg',
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-light-grey-wallpaper-04.jpg',
		],
	},
	{
		name: 'Markham',
		folder: 'markham',
		slug: 'markham',
		hero: 'upscale-hallway-wallpaper-installation-markham-modern-entry-corridor.jpg',
		gallery: [
			'upscale-hallway-wallpaper-installation-markham-modern-entry-corridor.jpg',
			'feature-wall-wallpaper-installation-markham.jpg',
			'bedroom-wallpaper-installation-markham-dark-botanical-feature-wall.jpg',
			'traditional-living-room-wallpaper-installation-markham-classic-floral-pattern.png',
			'executive-boardroom-wallpaper-installation-markham-modern-conference-space.png',
			'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
		],
	},
	{
		name: 'Aurora',
		folder: 'aurora',
		slug: 'aurora',
		hero: 'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
		gallery: [
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
		],
	},
	{
		name: 'King City',
		folder: 'king-city',
		slug: 'king-city',
		hero: 'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
		gallery: [
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'formal-dining-room-wallpaper-installation-vaughan-elegant-pattern.png',
			'custom-library-wallpaper-installation-richmond-hill-built-in-bookshelves.jpg',
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
		],
	},
	{
		name: 'Kleinburg',
		folder: 'kleinburg',
		slug: 'kleinburg',
		hero: 'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
		gallery: [
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'custom-library-wallpaper-installation-richmond-hill-built-in-bookshelves.jpg',
			'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-01.jpg',
		],
	},
	{
		name: 'Stouffville',
		folder: 'stouffville',
		slug: 'stouffville',
		hero: 'formal-dining-room-wallpaper-installation-vaughan-elegant-pattern.png',
		gallery: [
			'formal-dining-room-wallpaper-installation-vaughan-elegant-pattern.png',
			'dining-room-wallpaper-installation-vaughan-soft-floral-luxury-space.png',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
		],
	},
	{
		name: 'Woodbridge',
		folder: 'woodbridge',
		slug: 'woodbridge',
		hero: 'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-01.jpg',
		gallery: [
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-01.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-02.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-light-grey-wallpaper-04.jpg',
			'bathroom-wallpaper-installation-woodbridge-modern-01.jpg',
			'bathroom-wallpaper-installation-toronto-grey-pattern-feature-wall-01.jpg',
			'bathroom-wallpaper-installation-toronto-grey-pattern-feature-wall-02.jpg',
		],
	},
	{
		name: 'Mississauga',
		folder: 'mississauga',
		slug: 'mississauga',
		hero: 'striped-wallpaper-installation-mississauga-bedroom-neutral-vertical-lines.jpg',
		gallery: [
			'striped-wallpaper-installation-mississauga-bedroom-neutral-vertical-lines.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'wallpaper-installation-toronto-bedroom-feature-wall-01.jpg',
			'wallpaper-installation-toronto-bedroom-grey-texture-feature-wall.png',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
		],
	},
	{
		name: 'Oakville',
		folder: 'oakville',
		slug: 'oakville',
		hero: 'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
		gallery: [
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
			'traditional-living-room-wallpaper-installation-markham-classic-floral-pattern.png',
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
		],
	},
	{
		name: 'Burlington',
		folder: 'burlington',
		slug: 'burlington',
		hero: 'office-wallpaper-installation-vaughan-modern-commercial-interior.jpg',
		gallery: [
			'office-wallpaper-installation-vaughan-modern-commercial-interior.jpg',
			'home-office-wallpaper-installation-richmond-hill-bright-study-bookshelves.jpg',
			'executive-boardroom-wallpaper-installation-markham-modern-conference-space.png',
			'modern-boardroom-wallpaper-installation-toronto-contemporary-office.jpg',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
			'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
		],
	},
	{
		name: 'Etobicoke',
		folder: 'etobicoke',
		slug: 'etobicoke',
		hero: 'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
		gallery: [
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'upscale-hallway-wallpaper-installation-markham-modern-entry-corridor.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
			'bathroom-wallpaper-installation-toronto-grey-pattern-feature-wall-01.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-02.jpg',
		],
	},
	{
		name: 'Newmarket',
		folder: 'newmarket',
		slug: 'newmarket',
		hero: 'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
		gallery: [
			'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
			'formal-dining-room-wallpaper-installation-vaughan-elegant-pattern.png',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'custom-library-wallpaper-installation-richmond-hill-built-in-bookshelves.jpg',
		],
	},
	{
		name: 'Bradford',
		folder: 'bradford',
		slug: 'bradford',
		hero: 'dining-room-wallpaper-installation-vaughan-soft-floral-luxury-space.png',
		gallery: [
			'dining-room-wallpaper-installation-vaughan-soft-floral-luxury-space.png',
			'formal-dining-room-wallpaper-installation-vaughan-elegant-pattern.png',
			'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
		],
	},
	{
		name: 'Innisfil',
		folder: 'innisfil',
		slug: 'innisfil',
		hero: 'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
		gallery: [
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
		],
	},
	{
		name: 'Pickering',
		folder: 'pickering',
		slug: 'pickering',
		hero: 'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
		gallery: [
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
			'traditional-living-room-wallpaper-installation-markham-classic-floral-pattern.png',
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
			'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
		],
	},
	{
		name: 'Ajax',
		folder: 'ajax',
		slug: 'ajax',
		hero: 'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
		gallery: [
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'wallpaper-installation-toronto-bedroom-feature-wall-01.jpg',
			'wallpaper-installation-toronto-bedroom-grey-texture-feature-wall.png',
			'striped-wallpaper-installation-mississauga-bedroom-neutral-vertical-lines.jpg',
			'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
		],
	},
	{
		name: 'Whitby',
		folder: 'whitby',
		slug: 'whitby',
		hero: 'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
		gallery: [
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
			'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-light-grey-wallpaper-04.jpg',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
		],
	},
	{
		name: 'Oshawa',
		folder: 'oshawa',
		slug: 'oshawa',
		hero: 'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
		gallery: [
			'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
			'wallpaper-installation-toronto-bedroom-grey-texture-feature-wall.png',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
		],
	},
	{
		name: 'Forest Hill',
		folder: 'forest-hill',
		slug: 'forest-hill',
		hero: 'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
		gallery: [
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
			'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
		],
	},
	{
		name: 'Rosedale',
		folder: 'rosedale',
		slug: 'rosedale',
		hero: 'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
		gallery: [
			'elegant-dining-room-wallpaper-installation-toronto-classic-panel-look.png',
			'formal-dining-room-wallpaper-installation-vaughan-elegant-pattern.png',
			'elegant-living-room-wallpaper-installation-richmond-hill-soft-floral-design.png',
			'dramatic-foyer-wallpaper-installation-toronto-dark-floral-entry-console.png',
			'luxurious-living-room-wallpaper-installation-toronto-botanical-mural.png',
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
		],
	},
	{
		name: 'Leaside',
		folder: 'leaside',
		slug: 'leaside',
		hero: 'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
		gallery: [
			'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'bedroom-wallpaper-installation-markham-soft-textured-feature-wall.png',
			'dining-room-wallpaper-installation-vaughan-soft-floral-luxury-space.png',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-01.jpg',
		],
	},
	{
		name: 'The Beaches',
		folder: 'the-beaches',
		slug: 'the-beaches',
		hero: 'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
		gallery: [
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-02.jpg',
			'wallpaper-installation-toronto-bedroom-feature-wall-01.jpg',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
			'soft-kids-room-wallpaper-installation-richmond-hill-playful-floral.png',
			'modern-living-room-wallpaper-installation-vaughan-neutral-designer-wallpaper.png',
		],
	},
	{
		name: 'Caledon',
		folder: 'caledon',
		slug: 'caledon',
		hero: 'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
		gallery: [
			'silver-feature-wall-wallpaper-installation-markham-textured-metallic-finish.jpg',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
			'upscale-hallway-wallpaper-installation-markham-modern-entry-corridor.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-02.jpg',
			'bedroom-wallpaper-installation-vaughan-dark-floral-headboard-feature-wall.jpg',
			'landscape-wall-mural-installation-vaughan-mountain-scene-feature-wall.jpg',
		],
	},
	{
		name: 'Bolton',
		folder: 'bolton',
		slug: 'bolton',
		hero: 'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-02.jpg',
		gallery: [
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-02.jpg',
			'modern-bathroom-wallpaper-installation-woodbridge-vanity-feature-wall-01.jpg',
			'bathroom-wallpaper-installation-woodbridge-modern-01.jpg',
			'hallway-wallpaper-installation-toronto-modern-grey-corridor-feature-wall.jpg',
			'bedroom-wallpaper-installation-toronto-neutral-vertical-stripe-feature-wall-01.jpg',
			'textured-wallpaper-installation-richmond-hill-living-room-grey-feature-wall.jpg',
		],
	},
];
